### PR TITLE
Make flask-permissions work with an existing user table, rather than creating its own

### PR DESCRIPTION
**Pull request by bepetersn**
I wanted to use my own user table, and not have to work with the fp_user one.

### CODE REVIEW

**Comment by raddevon** [comment]
@bepetersn Thank you for the pull request. Could you see if you can get the build to pass the tests or refactor the tests if needed?

https://travis-ci.org/raddevon/flask-permissions/builds/110883672

**Comment by bepetersn** [comment]
@raddevon, 

I'll give it a shot. However, I think I would need to refactor, since 'UserMixin' is now abstract, and needs a model to inherit from it.

**Comment by christopher-abastar** [comment]
+1 to this 👍

**Comment by raddevon** [comment]
@christopher-abastar I doubt I'll have time in the near future to refactor this package, but I'd gladly accept a pull request. You might even want to check out @bepetersn's pull request and fork that for your PR. I believe he has added this, but it's not passing tests.

**Comment by bepetersn** [comment]
@raddevon Got the tests passing (soo much later).

**Comment by raddevon** [comment]
@bepetersn Awesome contribution! Thanks so much for dedicating your time and effort to this.

**Pull request merged**
